image: node:6
image: openjdk:8-jdk

cache:
  paths:
    - .gradle/

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ANDROID_SDK_TOOLS: "27.0.1"


before_script:
  #get android sdk
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -q android-sdk.zip -d android-sdk-linux

  - mkdir android-sdk-linux/licenses
  - printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
  - printf "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
  - android-sdk-linux/tools/bin/sdkmanager --update > update.log
  - android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log

  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

  #other
  - ping -c 1 aksw.org
  - chmod +x ./gradlew


#build_the_project:
#  script:
#    - sh program.sh
#    - test -f result.md

#release-job:
#  before_script:
#    - npm install -g markdown-pdf
#  script:
#    - sh program.sh
#    - markdown-pdf result.md
#    - markdown-pdf Webseiten/docu.md
#    - mv Webseiten/docu.pdf docu.pdf
#  artifacts:
#    paths:
#    - result.pdf
#    - docu.pdf
#  only:
#    - tags

CodeStyle:
  script:
    - ./gradlew checkStylecheck
  allow_failure: true

ServerTest:
  script:
    - ./gradlew checkServerTests